apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: default
  namespace: acd
spec:
  project: default
  source:
    chart: acd-helm
    repoURL: https://monzy-b.github.io/helm-repo/
    targetRevision: 0.1.0
    helm:
      releaseName: acd-helm
      valueFiles: 
       - ./values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: acd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
